# Generated by Django 6.0.2 on 2026-02-20 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('party', models.CharField(choices=[('BJP', 'BJP'), ('Congress', 'Congress'), ('JDS', 'JDSB'), ('BSP', 'BSP')], max_length=20)),
                ('location', models.CharField(choices=[('Doranahalli', 'Doranahalli'), ('Shahapur', 'Shahapur'), ('Jayanagar', 'Jayanagar'), ('Vasantapura', 'Vasantapura'), ('Hosur', 'Hosur')], max_length=50)),
                ('votes', models.IntegerField(default=0)),
                ('party_logo', models.ImageField(blank=True, null=True, upload_to='party_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voting_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('voter_id', models.CharField(max_length=10, unique=True)),
                ('has_voted', models.BooleanField(default=False)),
                ('voted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18)])),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('reset_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreApprovedVoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('voter_id', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('aadhaar_number', 'voter_id', 'location')},
            },
        ),
    ]
